// Date()
let dateNow = new Date()
console.log(dateNow)
// Date.now() mille sacond
console.log(Date.now())
// Date.getTime() return date milleSacond
console.log(dateNow.getTime())
// getDate() 
console.log(dateNow.getDate())
// getFullYear()
console.log(dateNow.getFullYear())
// getMonth()
console.log(dateNow.getMonth())
// getDay()
console.log(dateNow.getDay())
